//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalProvEntities : DbContext
    {
        public PortalProvEntities()
            : base("name=PortalProvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<PPROV_Adjuntos> PPROV_Adjuntos { get; set; }
        public virtual DbSet<PPROV_Contrasena> PPROV_Contrasena { get; set; }
        public virtual DbSet<PPROV_Documento> PPROV_Documento { get; set; }
        public virtual DbSet<PPROV_Estado> PPROV_Estado { get; set; }
        public virtual DbSet<PPROV_Nota> PPROV_Nota { get; set; }
        public virtual DbSet<PPROV_Retenciones> PPROV_Retenciones { get; set; }
        public virtual DbSet<PPROV_RetencionTipo> PPROV_RetencionTipo { get; set; }
        public virtual DbSet<PPROV_TipoAdjunto> PPROV_TipoAdjunto { get; set; }
        public virtual DbSet<GEN_Configuracion> GEN_Configuracion { get; set; }
        public virtual DbSet<GEN_Audit> GEN_Audit { get; set; }
        public virtual DbSet<GEN_Catalogo> GEN_Catalogo { get; set; }
        public virtual DbSet<GEN_CatalogoDetalle> GEN_CatalogoDetalle { get; set; }
        public virtual DbSet<GEN_Menu> GEN_Menu { get; set; }
        public virtual DbSet<V_GEN_MenuDisplay> V_GEN_MenuDisplay { get; set; }
        public virtual DbSet<V_GEN_RolesDelMenu> V_GEN_RolesDelMenu { get; set; }
        public virtual DbSet<V_GEN_UsuarioMenuPerfil> V_GEN_UsuarioMenuPerfil { get; set; }
        public virtual DbSet<V_GEN_UsuarioRoles> V_GEN_UsuarioRoles { get; set; }
        public virtual DbSet<V_GEN_UsuarioRoles_Diponibles> V_GEN_UsuarioRoles_Diponibles { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
