//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PortalProvEntities : DbContext
    {
        public PortalProvEntities()
            : base("name=PortalProvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<GEN_Configuracion> GEN_Configuracion { get; set; }
        public virtual DbSet<GEN_Audit> GEN_Audit { get; set; }
        public virtual DbSet<GEN_Catalogo> GEN_Catalogo { get; set; }
        public virtual DbSet<GEN_CatalogoDetalle> GEN_CatalogoDetalle { get; set; }
        public virtual DbSet<GEN_Menu> GEN_Menu { get; set; }
        public virtual DbSet<V_GEN_MenuDisplay> V_GEN_MenuDisplay { get; set; }
        public virtual DbSet<V_GEN_RolesDelMenu> V_GEN_RolesDelMenu { get; set; }
        public virtual DbSet<V_GEN_UsuarioMenuPerfil> V_GEN_UsuarioMenuPerfil { get; set; }
        public virtual DbSet<V_GEN_UsuarioRoles> V_GEN_UsuarioRoles { get; set; }
        public virtual DbSet<V_GEN_UsuarioRoles_Diponibles> V_GEN_UsuarioRoles_Diponibles { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<PPROV_Adjuntos> PPROV_Adjuntos { get; set; }
        public virtual DbSet<PPROV_Estado> PPROV_Estado { get; set; }
        public virtual DbSet<PPROV_RetencionTipo> PPROV_RetencionTipo { get; set; }
        public virtual DbSet<PPROV_TipoAdjunto> PPROV_TipoAdjunto { get; set; }
        public virtual DbSet<PPROV_Documento> PPROV_Documento { get; set; }
        public virtual DbSet<v_PPROV_FacturasIngresadasPorUsuario> v_PPROV_FacturasIngresadasPorUsuario { get; set; }
        public virtual DbSet<V_PPROV_Contrasena_PorUsuario> V_PPROV_Contrasena_PorUsuario { get; set; }
        public virtual DbSet<V_PPROV_DocumentosPorUsuario> V_PPROV_DocumentosPorUsuario { get; set; }
        public virtual DbSet<V_PPROV_RetencionesPorUsuario> V_PPROV_RetencionesPorUsuario { get; set; }
        public virtual DbSet<V_PPROV_Contrasena_Oficina> V_PPROV_Contrasena_Oficina { get; set; }
        public virtual DbSet<V_PPROV_Documentos_Oficina> V_PPROV_Documentos_Oficina { get; set; }
        public virtual DbSet<v_PPROV_FacturasIngresadas_Oficina> v_PPROV_FacturasIngresadas_Oficina { get; set; }
        public virtual DbSet<V_PPROV_Retenciones_Oficina> V_PPROV_Retenciones_Oficina { get; set; }
        public virtual DbSet<V_PPROV_ResumenEstadoDocumento> V_PPROV_ResumenEstadoDocumento { get; set; }
        public virtual DbSet<PPROV_Nota> PPROV_Nota { get; set; }
        public virtual DbSet<PPROV_UsuarioProveedor> PPROV_UsuarioProveedor { get; set; }
        public virtual DbSet<v_PPROV_Usuario_Proveedor> v_PPROV_Usuario_Proveedor { get; set; }
        public virtual DbSet<V_PPROV_Proveedor> V_PPROV_Proveedor { get; set; }
        public virtual DbSet<PPROV_UsuarioEmpresa> PPROV_UsuarioEmpresa { get; set; }
        public virtual DbSet<V_PPROV_Empresas> V_PPROV_Empresas { get; set; }
        public virtual DbSet<PPROV_Contrasena> PPROV_Contrasena { get; set; }
        public virtual DbSet<PPROV_Retencion> PPROV_Retencion { get; set; }
    
        public virtual ObjectResult<SP_PPROV_STATS_FacturacionUltimoAnio_Result> SP_PPROV_STATS_FacturacionUltimoAnio(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_STATS_FacturacionUltimoAnio_Result>("SP_PPROV_STATS_FacturacionUltimoAnio", userNameParameter);
        }
    
        public virtual ObjectResult<SP_PPROV_Indicadores_Usuario_Result> SP_PPROV_Indicadores_Usuario(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_Indicadores_Usuario_Result>("SP_PPROV_Indicadores_Usuario", userNameParameter);
        }
    
        public virtual ObjectResult<SP_PPROV_DatosOrdenCompra_Result> SP_PPROV_DatosOrdenCompra(Nullable<int> docnum)
        {
            var docnumParameter = docnum.HasValue ?
                new ObjectParameter("Docnum", docnum) :
                new ObjectParameter("Docnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_DatosOrdenCompra_Result>("SP_PPROV_DatosOrdenCompra", docnumParameter);
        }
    
        public virtual ObjectResult<SP_PPROV_PermisosCodigosProv_Usuario_Result> SP_PPROV_PermisosCodigosProv_Usuario(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_PermisosCodigosProv_Usuario_Result>("SP_PPROV_PermisosCodigosProv_Usuario", usernameParameter);
        }
    
        public virtual ObjectResult<SP_REP_Contrasena_Detalle_Result> SP_REP_Contrasena_Detalle(Nullable<System.Guid> contrasena_Id)
        {
            var contrasena_IdParameter = contrasena_Id.HasValue ?
                new ObjectParameter("Contrasena_Id", contrasena_Id) :
                new ObjectParameter("Contrasena_Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REP_Contrasena_Detalle_Result>("SP_REP_Contrasena_Detalle", contrasena_IdParameter);
        }
    
        public virtual ObjectResult<SP_REP_Contrasena_Encabezado_Result> SP_REP_Contrasena_Encabezado(Nullable<System.Guid> contrasena_Id)
        {
            var contrasena_IdParameter = contrasena_Id.HasValue ?
                new ObjectParameter("Contrasena_Id", contrasena_Id) :
                new ObjectParameter("Contrasena_Id", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_REP_Contrasena_Encabezado_Result>("SP_REP_Contrasena_Encabezado", contrasena_IdParameter);
        }
    
        public virtual ObjectResult<SP_PPROV_ADM_EmpresasOficina_Result> SP_PPROV_ADM_EmpresasOficina(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_ADM_EmpresasOficina_Result>("SP_PPROV_ADM_EmpresasOficina", usernameParameter);
        }
    
        public virtual ObjectResult<SP_PPROV_Indicadores_Oficina_Result> SP_PPROV_Indicadores_Oficina(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PPROV_Indicadores_Oficina_Result>("SP_PPROV_Indicadores_Oficina", userNameParameter);
        }
    }
}
