//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEL_Doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FEL_Doc()
        {
            this.FEL_DocDetalle = new HashSet<FEL_DocDetalle>();
        }
    
        public System.Guid FEL_Unique { get; set; }
        public int Correlativo { get; set; }
        public string Bodega { get; set; }
        public string TipoDoc { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
        public string Nit { get; set; }
        public string CardCode { get; set; }
        public string Cardname { get; set; }
        public string Moneda { get; set; }
        public decimal Total { get; set; }
        public string Tipo_Detalle { get; set; }
        public string Estado { get; set; }
        public string SyncSapId { get; set; }
        public string SyncSapDate { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<System.Guid> DepartamentoId { get; set; }
        public Nullable<decimal> TasaCambio { get; set; }
        public string Referencia { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
        public string ActualizadoPor { get; set; }
        public Nullable<System.DateTime> ActualizadoEl { get; set; }
        public string AutorizadoPor { get; set; }
        public Nullable<System.DateTime> AutorizadoEl { get; set; }
        public string SincronizadoPor { get; set; }
        public Nullable<System.DateTime> SincronizadoEl { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> EnvioAuto { get; set; }
        public Nullable<int> EntregaNo { get; set; }
        public Nullable<System.DateTime> EntregaEl { get; set; }
        public string EntregaPor { get; set; }
        public Nullable<bool> ActivoFijo { get; set; }
        public string EntregaMultiple { get; set; }
        public Nullable<decimal> EntregaSaldo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FEL_DocDetalle> FEL_DocDetalle { get; set; }
    }
}
