//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEL_DocDetalle
    {
        public System.Guid FEL_Unique { get; set; }
        public int Linea { get; set; }
        public string TipoDet { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string UnidadMedida { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Descuentos { get; set; }
        public decimal TotalLinea { get; set; }
        public decimal Impuestos { get; set; }
        public System.DateTime DateAudit { get; set; }
        public string UserNameAudit { get; set; }
        public Nullable<decimal> DescuentoPU { get; set; }
        public string TipoImpuesto { get; set; }
        public string CentroCosto { get; set; }
        public string CuentaContable { get; set; }
        public string Bodega { get; set; }
        public Nullable<int> BaseEntry { get; set; }
        public Nullable<int> BaseLine { get; set; }
        public Nullable<int> BaseType { get; set; }
    
        public virtual FEL_Doc FEL_Doc { get; set; }
    }
}
