//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEL_DocAdjunto
    {
        public System.Guid AdjuntoId { get; set; }
        public System.Guid FEL_Unique { get; set; }
        public string AdjuntoTipo { get; set; }
        public System.DateTime AdjuntoFecha { get; set; }
        public string AdjuntoRuta { get; set; }
        public string NombreOriginal { get; set; }
        public string UserName { get; set; }
    }
}
