//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEL_DocHistorico
    {
        public System.Guid Fel_Unique { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Tipo { get; set; }
        public string Estado_Original { get; set; }
        public string Estado_Destino { get; set; }
        public string Usuario { get; set; }
        public string Observaciones { get; set; }
    }
}
