//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_Empresa
    {
        public int EmpresaId { get; set; }
        public string EmpresaNombre { get; set; }
        public System.Guid EmpresaGuid { get; set; }
        public string EmpresaNit { get; set; }
        public string EmpresaLogo { get; set; }
        public string EmpresaCorreo { get; set; }
        public string EmpresaTel { get; set; }
        public string EmpresaDireccion { get; set; }
        public string SAP_Server { get; set; }
        public string SAP_DBUserName { get; set; }
        public string SAP_DBPassword { get; set; }
        public string SAP_Database { get; set; }
        public string Tema { get; set; }
        public string EmpresaOCCheck { get; set; }
        public Nullable<bool> EntregaRequerida { get; set; }
        public string EmpresaAsuntoCorreo { get; set; }
    }
}
