//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_Menu()
        {
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public System.Guid Menu_Id { get; set; }
        public string Menu_Nombre { get; set; }
        public string Menu_Url { get; set; }
        public string Menu_Icons { get; set; }
        public Nullable<System.Guid> Menu_Parent { get; set; }
        public string Menu_Target { get; set; }
        public Nullable<int> Menu_Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
