//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CatalogoDetalle
    {
        public Nullable<int> Catalogo_Id { get; set; }
        public int CatalogoDetalleId { get; set; }
        public string Nombre { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Orden { get; set; }
        public string ParentValor { get; set; }
        public Nullable<bool> Sistema { get; set; }
        public string Parametro1 { get; set; }
        public string Parametro2 { get; set; }
    
        public virtual GEN_Catalogo GEN_Catalogo { get; set; }
    }
}
