//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_Catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_Catalogo()
        {
            this.GEN_CatalogoDetalle = new HashSet<GEN_CatalogoDetalle>();
        }
    
        public int Catalogo_Id { get; set; }
        public string Catalogo_Nombre { get; set; }
        public int Catalogo_Orden { get; set; }
        public string Nombre_ParentId { get; set; }
        public string Nombre_Parametro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_CatalogoDetalle> GEN_CatalogoDetalle { get; set; }
    }
}
