//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionesCola
    {
        public System.Guid Id { get; set; }
        public string Para { get; set; }
        public string Copia { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<System.DateTime> EnviadoFecha { get; set; }
        public Nullable<System.DateTime> ProximoEnvio { get; set; }
        public Nullable<System.DateTime> EnviarHasta { get; set; }
        public Nullable<int> IntervaloMinutos { get; set; }
        public string Sistema { get; set; }
        public string Parametro1 { get; set; }
        public string Parametro2 { get; set; }
    }
}
