//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROV_TipoAdjunto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPROV_TipoAdjunto()
        {
            this.PPROV_Adjuntos = new HashSet<PPROV_Adjuntos>();
        }
    
        public System.Guid Adjunto_Tipo { get; set; }
        public string Adjunto_Nombre { get; set; }
        public string Extension { get; set; }
        public bool Agrega_Prov { get; set; }
        public bool Agregar_Empresa { get; set; }
        public bool Requerido_Prov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPROV_Adjuntos> PPROV_Adjuntos { get; set; }
    }
}
