//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROV_Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPROV_Documento()
        {
            this.PPROV_Adjuntos = new HashSet<PPROV_Adjuntos>();
            this.PPROV_Nota = new HashSet<PPROV_Nota>();
            this.PPROV_Retencion = new HashSet<PPROV_Retencion>();
        }
    
        public System.Guid Doc_Id { get; set; }
        public string Doc_CardCorde { get; set; }
        public string Doc_Estado { get; set; }
        public string Doc_Numero { get; set; }
        public string Doc_Serie { get; set; }
        public Nullable<System.DateTime> Doc_Fecha { get; set; }
        public Nullable<int> Doc_EmpresaId { get; set; }
        public Nullable<decimal> Doc_MontoNeto { get; set; }
        public string Doc_Moneda { get; set; }
        public string Doc_Autorizacion { get; set; }
        public string Doc_Observaciones { get; set; }
        public string Doc_TipoDocumento { get; set; }
        public string Doc_UsuarioCarga { get; set; }
        public Nullable<System.DateTime> Doc_FechaCarga { get; set; }
        public Nullable<int> Doc_NumeroOC { get; set; }
        public Nullable<int> Doc_NumeroFactProv { get; set; }
        public Nullable<int> Doc_NumeroEntrega { get; set; }
        public Nullable<System.Guid> Contrasena_Id { get; set; }
        public string Doc_PdfFactura { get; set; }
        public string Doc_PdfOC { get; set; }
        public string SolicitanteOC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPROV_Adjuntos> PPROV_Adjuntos { get; set; }
        public virtual PPROV_Contrasena PPROV_Contrasena { get; set; }
        public virtual PPROV_Estado PPROV_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPROV_Nota> PPROV_Nota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPROV_Retencion> PPROV_Retencion { get; set; }
    }
}
