//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROV_Contrasena
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PPROV_Contrasena()
        {
            this.PPROV_Documento = new HashSet<PPROV_Documento>();
        }
    
        public System.Guid Contrasena_Id { get; set; }
        public int Contrasena_Numero { get; set; }
        public int Empresa_Id { get; set; }
        public System.DateTime Contrasena_Fecha { get; set; }
        public System.DateTime Contrasena_Fecha_Estimada { get; set; }
        public string Contrasena_Usuario { get; set; }
        public string Contrasena_Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PPROV_Documento> PPROV_Documento { get; set; }
    }
}
