//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROV_Adjuntos
    {
        public System.Guid Adjunto_Id { get; set; }
        public System.Guid Doc_Id { get; set; }
        public string Adjunto_FileName { get; set; }
        public Nullable<System.Guid> Adjunto_Tipo { get; set; }
    
        public virtual PPROV_Documento PPROV_Documento { get; set; }
        public virtual PPROV_TipoAdjunto PPROV_TipoAdjunto { get; set; }
    }
}
