//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPROV_UsuarioDepartamento
    {
        public string UserId { get; set; }
        public System.Guid DepartmentId { get; set; }
        public int Empresa_Id { get; set; }
        public bool Crear { get; set; }
        public bool Autorizar { get; set; }
    }
}
