//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GEN_UsuarioRoles_Diponibles
    {
        public string UserId { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string UserNameAudit { get; set; }
        public Nullable<bool> Sistema { get; set; }
    }
}
