//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GEN_UsuarioMenuPerfil
    {
        public string UserName { get; set; }
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public System.Guid Menu_Id { get; set; }
        public string Menu_Nombre { get; set; }
        public string Menu_Url { get; set; }
        public string Menu_Icons { get; set; }
        public Nullable<System.Guid> Menu_Parent { get; set; }
        public string Menu_Target { get; set; }
        public Nullable<int> Menu_Orden { get; set; }
    }
}
