//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PPROV_InsumosPendientes
    {
        public string U_FacNum { get; set; }
        public Nullable<int> EM_DocNum { get; set; }
        public int EM_DocEntry { get; set; }
        public Nullable<decimal> EM_DocTotal { get; set; }
        public Nullable<int> EM_BaseEntry { get; set; }
        public Nullable<int> EM_BaseType { get; set; }
        public string EM_CardCode { get; set; }
        public string EM_CardName { get; set; }
        public Nullable<int> OC_DocNum { get; set; }
        public Nullable<int> OC_DocEntry { get; set; }
        public Nullable<decimal> OC_DocTotal { get; set; }
        public Nullable<int> FAP_DocEntry { get; set; }
        public Nullable<int> FAP_DocNum { get; set; }
        public Nullable<decimal> FAP_Doctotal { get; set; }
        public string U_FELUUID { get; set; }
        public string U_FELNumero { get; set; }
        public string U_FELSerie { get; set; }
        public string U_FELFecha { get; set; }
        public string FAP_DocCur { get; set; }
    }
}
