//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PPROV_FacturasIngresadasPorUsuario
    {
        public long RowNbr { get; set; }
        public string UserName { get; set; }
        public Nullable<int> BPLId { get; set; }
        public string TrsfrRef { get; set; }
        public Nullable<System.DateTime> TrsfrDate { get; set; }
        public Nullable<decimal> TrsfrSum { get; set; }
        public string DocCurr { get; set; }
        public string Tipo { get; set; }
        public string U_FacSerie { get; set; }
        public string U_Facnum { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string DocCur { get; set; }
        public Nullable<decimal> Retenciones { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
        public Nullable<int> DocNum { get; set; }
        public int DocEntry { get; set; }
        public Nullable<decimal> MontoTrans { get; set; }
        public string Empresa_Name { get; set; }
        public Nullable<int> U_NumContrase { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public decimal Monto_Nota { get; set; }
    }
}
