//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PPROV_ResumenEstadoDocumento
    {
        public string Doc_Estado { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> Doc_Orden { get; set; }
    }
}
