//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PPROV_Empresas
    {
        public long RowNbr { get; set; }
        public int Empresa_Id { get; set; }
        public string Empresa_Name { get; set; }
        public string Nit { get; set; }
        public string AliasName { get; set; }
    }
}
