//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PPROV_RetencionesPorUsuario
    {
        public long RowNbr { get; set; }
        public string UserName { get; set; }
        public string Doc_Serie { get; set; }
        public string Doc_Numero { get; set; }
        public string Doc_TipoDocumento { get; set; }
        public System.Guid Retencion_Id { get; set; }
        public string Retencion_Numero { get; set; }
        public Nullable<System.DateTime> Retencion_Fecha { get; set; }
        public Nullable<int> Retencion_Tipo { get; set; }
        public string Retencion_Usuario { get; set; }
        public Nullable<decimal> Retencion_Monto { get; set; }
        public string Retencion_Moneda { get; set; }
        public string Retencion_Pdf { get; set; }
        public string Retencion_Nombre { get; set; }
        public string Empresa_Name { get; set; }
    }
}
