//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PPROV_Contrasena_PorUsuario
    {
        public long RowNbr { get; set; }
        public string UserName { get; set; }
        public string Empresa_Name { get; set; }
        public System.Guid Contrasena_Id { get; set; }
        public int Contrasena_Numero { get; set; }
        public int Empresa_Id { get; set; }
        public System.DateTime Contrasena_Fecha { get; set; }
        public System.DateTime Contrasena_Fecha_Estimada { get; set; }
        public string Contrasena_Usuario { get; set; }
        public string Contrasena_Estado { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public string Contrasena_CardCode { get; set; }
        public string Contrasena_Moneda { get; set; }
        public string Facturas { get; set; }
    }
}
