//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wareways.PortalProv.Infraestructura
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PROV_EmpresaUltiDia_Rece
    {
        public System.Guid Id { get; set; }
        public string CardCode { get; set; }
        public int Mes { get; set; }
        public string Anio { get; set; }
        public int Dia { get; set; }
        public string Mensaje { get; set; }
        public bool Activo { get; set; }
        public string CardName { get; set; }
        public Nullable<int> DiaServ { get; set; }
    }
}
